# Generated by Django 4.2.3 on 2023-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shamba",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
